#! /bin/sh
#
# setting up lowpan interface
echo Setting up lowpan interface
set -x #echo on

sudo kill -s KILL `pgrep ifplugd`
sudo ip link set wpan0 down
sudo ip link set lowpan0 down

# set channel
sudo iwpan phy phy0 set channel 0 26
sudo ip link add link wpan0 name lowpan0 type lowpan
# set pan_id
sudo iwpan dev wpan0 set pan_id 0x23
sudo ip link set wpan0 up
sudo ip link set lowpan0 up
sudo modprobe ipv6

# disable udp header compression
sudo rmmod nhc_udp
